<?php

declare(strict_types=1);

use Kodhe\Framework\Database\Loader;

/**
 * Migration: create articles table.
 *
 * Generated by `php console make:crud` — uses the modern Kodhe Database
 * component (driver-level Forge via Loader::dbforge()), not the legacy
 * CI3 dbutil.
 */
return new class {

    public function up(): void
    {
        // Ambil forge dari koneksi aktif via Kodhe Database Loader (modern stack).
        $forge = Loader::dbforge(null, true);

        // Idempoten: lewatkan pembuatan jika tabel sudah ada. Tanpa guard ini,
        // re-run migration bisa meninggalkan state setengah jadi yang memicu
        // error "no tables specified" / query gagal di endpoint articles.
        // Catatan penting:
        //  - table_exists() tersedia di Connection (ConnectionAbstract),
        //    BUKAN di driver Forge -> $forge->table_exists() fatal.
        //  - Properti $db pada Blueprint/Forge bersifat protected
        //    -> $forge->db->... fatal "Cannot access protected property".
        //    Akses resmi kini via $forge->connection() (method publik baru di
        //    Blueprint). Fallback ke kodhe()->db bila method belum tersedia
        //    (mis. vendor symlink belum ter-update).
        $connection = method_exists($forge, 'connection')
            ? $forge->connection()
            : (\class_exists('Kodhe\Framework\Database\Loader', false) ? \kodhe()->db : null);

        if ($connection !== null && $connection->table_exists('articles')) {
            return;
        }

        $forge->add_field([
            'id' => ['type' => 'INT', 'constraint' => 9, 'unsigned' => TRUE, 'auto_increment' => TRUE],
            'title' => ['type' => 'VARCHAR', 'constraint' => 255, 'null' => TRUE],
            'slug' => ['type' => 'VARCHAR', 'constraint' => 255, 'null' => TRUE],
            'body' => ['type' => 'TEXT', 'null' => TRUE],
            'published' => ['type' => 'TINYINT', 'constraint' => 1, 'null' => TRUE],
            'created_at' => ['type' => 'DATETIME', 'null' => TRUE],
            'updated_at' => ['type' => 'DATETIME', 'null' => TRUE],
        ]);

        $forge->add_key('id', TRUE);
        // Index slug: lookup by slug (GET /articles/{id-or-slug}) & anti-duplikasi.
        $forge->add_key('slug');
        $forge->create_table('articles', TRUE);
    }

    public function down(): void
    {
        $forge = Loader::dbforge(null, true);
        $forge->drop_table('articles', TRUE);
    }
};
